### ISSUE TITLE
robotskirt module ::: node_modules 에서 제외 ::: make gen 에러

### ISSUE THREAD

**Issue by nanha** [rhiokim/haroopress#185]
robotskirt.node파일이 아마 darwin에서 빌드된 상태라

linux 플랫폼에서 사용하게 되면 공유객체를 사용할 수 없는 상태.

rebuild 해야함.

즉, node_modules에서 제거하고, npm install 과정에 포함시켜 waf rebuild가 해당 플랫폼에 맞게 rebuild 되어야 함.

현재는 linux platform에서 에러발생 robotskirt module을 다시 설치해서 조치했음

**Comment by rhiokim** [comment]
roboskirt 는 markdown native 모듈로 현재 성능이 가장 빨라서 선택했으나...
약간의 버그가 있어 변경을 고려중이에요. 그리고 타 플랫폼 지원 시 문제가 더 발생할 것 같아서
서버 클라이언트 동시에 사용할 수 있는 성능이 뛰어나고 기왕이면 multimarkdown 을 지원하는 녀석으로 
선택적으로 가져갈 계획이에요.

**Comment by rhiokim** [comment]
멀티마크 다운 지원과 함께 개선될 예정, 마일스톤 이동합니다.

**Comment by andrwj** [comment]
배포본의 master 브랜치를 로컬 브랜치로 merge 하지 않고  Ubuntu 리눅스에서 robotskirt 관련 오류는 다음과 같이 간단히 해결할 수 있습니다.
- 자신의 로컬 Haroopress 설치 최상위 폴더 아래의 robotskirt 폴더로 이동
- robotskirt 모듈을 다시 빌드한후 
- Haroopress 최상위 폴더로 이동하여 `make gen` 명령등을 실행

> `node install node-gyp -g` 명령은 node-gyp 명령이 없을 경우에만 실행하세요

```
$ cd root-of-path-to-Haroopress-installation
$ cd node_modules/robotskirt/
$ npm install node-gyp -g
$ node-gyp rebuild
```

**Comment by rhiokim** [comment]
robotskirt 모듈이 최근 node-gyp 지원을 하기 시작했는데 master 브랜치에는 작업이 안되어 있는 상태였네요.
robotskirt 만 master 브랜치에 핫픽스로 업데이트하고

make init 시점에서 robotskirt 모듈을 rebuild 하도록 개선하였습니다.

**Comment by rhiokim** [comment]
이 이슈는 해결처리합니다.
