### ISSUE TITLE
node v0.8.1 ::: locally 설치 에러로 인해 make init 실패

### ISSUE THREAD

**Issue by nanha** [rhiokim/haroopress#188]
# 원인

commander 의 버젼문제
# 배경

현재 npm 에 publish된 버젼은 0.8.1에서 설치가 안됨 (npm install commander)
# 임시조치

locally fork 받아 https://github.com/nanha/locally/blob/master/package.json 파일에 commander dependency 주소를 변경
haroopress에서 locally 주소 변경

npm:
  @echo "========================================"
  @echo "= setup npm dependency module"
  @echo "========================================"
  npm install -g express
  npm install -g less
  npm install -g uglify-js
  npm install -g git://github.com/nanha/locally.git
# 결론

일단 잘 된다. ㅋㅋㅋ

**Comment by rhiokim** [comment]
버젼 이슈로 최신의 노드에서는 발생하지 않는 문제입니다.
