### ISSUE TITLE
body 안에 link  태그 질문

### ISSUE THREAD

**Issue by J2P** [rhiokim/haroopress#253]
소스를 보니까 
<link href="/css/code/rainbow.css" rel="stylesheet"> 요것이 body 안에 들어가 있던데요
head 안에 있는데 body 안에 또 들어간 이유가 있을까요??

**Comment by rhiokim** [comment]
하루프레스는 config.js 에 설정한 `defaultCodeStyle` 외에 각 포스트 별로 스타일을 재 정의할 수 있도록 되어 있어요.

config.js 에 지정한 것은 전역적으로 적용되고 각 포스트 메타 정보에 추가된 `advanced: { codeStyle: 'rainbow' }` 는 각 포스트에만 적용되는 스타일입니다.

궁금증이 풀리셨다면 이슈 닫아 주시고 아니면 댓글 더 남겨주세요. ^_^/

**Comment by J2P** [comment]
와... 그런 멋진 기능이 였군요~
빠른 답변 감사합니다 :+1:
