### ISSUE TITLE
하루프레스 설치시 에러 발생

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopress#254]
하루프레스를 git clone 한 후에  make init을 하면 도중에 에러가 발생합니다.
# 
# = configurate haroopress

./bin/setup.js
env: node: No such file or directory
make: **\* [setup] Error 127

확인 부탁드립니다.

**Comment by rhiokim** [comment]
혹시 플랫폼(운영체제)를 알 수 있을까요?

위의 문제는 `/usr/bin/` 위치에 `env` 가 존재하지 않아서 발생하는 문제로 보이는데요.
리눅스의 경우 `env` 지정하는 방식이 달랐던 것으로 기업합니다. 

**하루프레스는 현재 Mac OS 에서만 지원하고 크로스 플랫폼(리눅스, 윈도우) 지원은 11월부터 개발 진행될 예정입니다.**

**Comment by ghost** [comment]
저는 **Mac OS 10.8.2** 를 사용하고 있구요. 

하루프레스 0.8 버전을 설치할 때는 저런 문제가 발생하지 않았었는데.
오늘 이전버전을 삭제하고 새로 내려받았는데 저런 에러가 발생하더라구요.

**Comment by rhiokim** [comment]
다시 보니 env 의 문제가 아니라 node 문제로 보이네요.

`$ env node` 실행 시 동일한 문제가 발생하면 콘솔에서 node 가 path 로 설정되지 않았을 것 같네요.

> 하루프레스 설치 시  에러 리포팅을 위한 내부 기능을 최대한 빨리 구현해야 겠네요.

**Comment by ghost** [comment]
아! 죄송합니다.
nvm이 자동으로 시작되도록 설정을 안해놔서 재부팅 했더니 nvm이 꺼져있어서 발생한 오류였습니다.
혼란을 드려서 죄송합니다!

**Comment by rhiokim** [comment]
죄송은요.. :-)

아시겠지만 다른 사용자들을 위해 추가합니다.

nvm 으로 노드 설치 후 꼭 해줘야 할 내용은 아래와 같이 nvm.sh 파일을 path 로 잡아 주는 것입니다.

`$ echo ". ~/nvm/nvm.sh" >> ~/.bash_profile` 

그리고 여러 버젼을 설치해 사용할 때 default 를 설정해 주는 것이 좋습니다.

`$ nvm alias default 0.8.12`

이렇게 2가지를 설정하게 되면 OS 를 재부팅하면 nvm 이 자동으로 올라오고 node 도 default 버젼으로 설정됩니다.

이슈 종료합니다.

**Comment by ghost** [comment]
친절하신 설명 감사드립니다! :)
