### ISSUE TITLE
cname 설정에 대하여

### ISSUE THREAD

**Issue by imtaehyun** [rhiokim/haroopress#261]
도메인을 github페이지로 설정하려고 cname설정을 도메인에 해 놨는데요. 404에러페이지가 나오네요.
하루프레스 메인페이지에 설정하는 링크를 보니까 page 메인에 CNAME이라는 파일을 만들어야 한다고 되어있는데 그것때문일까요? 도통 CNAME파일을 만들어 넣는 방법을 잘 모르겠습니다.

**Comment by rhiokim** [comment]
config.js 파일을 열어보시면 CNAME 필드가 있어요 그 값에 도메인(예 haroopress.com)을 지정하시면 deploy 시 자동으로 생성합니다

**Comment by imtaehyun** [comment]
아 그렇군요. 감사합니다!

**Comment by rhiokim** [comment]
직접 메뉴얼도 작성해주시고 너무 감사드립니다. :+1: 
이 이슈는 닫도록 하겠습니다.

http://nezz.pe.kr/post/harupeureseu-gaeindomein-seoljeongbangbeob/
