### ISSUE TITLE
코멘트 갯수가 제대로 표시되지 않는 버그

### ISSUE THREAD

**Issue by imtaehyun** [rhiokim/haroopress#263]
http://nezz.pe.kr/post/harupeureseu-gaeindomein-seoljeongbangbeob 를 보시면 rhiokim님과 제가 작성한 댓글이 있음에도 불구하고 http://nezz.pe.kr 에서 보면 `0 comments`라고 표현됩니다.

아직 구현이 안된부분인가요? 아님 버그인가요? 확인부탁드립니다. ^^

오늘도 좋은하루 되세요!

**Comment by rhiokim** [comment]
인지하고 있는 버그 맞습니다. :-) 디스커스 연동 방법이 있는데 제대로 동작을 안하더라구요. ;-) 

사소한 버그니 최대한 빨리 대응 해볼께요. 감사합니다.

**Comment by juhoi** [comment]
main.ejs 파일 39라인의 #disqus_thread 링크 해주는 곳에 data-disqus-identifier 속성을 빼주니 count 표시 되는 것 같습니다. 근데 빼주는게 맞는건지... http://juhoi.github.com
