### ISSUE TITLE
plugin 개발시 core와의 Dependency 해지방안 ㅋ

### ISSUE THREAD

**Issue by insanehong** [rhiokim/haroopress#276]
현재 구조로는 좀 어러운 문제인거는 같은데

플러그인을 개발하여 하루프레스에 append 시키고 싶을때

플러그인을 위해 core가 수정되어야 하는 문제에 대해

plugin 영역을 분리해서 append 시킬수 있는 방안이 필요할듯.

**Comment by rhiokim** [comment]
아주 먼 미래가 될것 같네요. 우선 백로그로 ^_^;;
