### ISSUE TITLE
make init 을 root권한으로 실행해야하나요?

### ISSUE THREAD

**Issue by hjazz** [rhiokim/haroopress#277]
make init

npm install -g node-gyp
npm http GET https://registry.npmjs.org/node-gyp
npm http 200 https://registry.npmjs.org/node-gyp
npm http GET https://registry.npmjs.org/node-gyp/-/node-gyp-0.8.1.tgz
npm http 200 https://registry.npmjs.org/node-gyp/-/node-gyp-0.8.1.tgz
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/node-gyp'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/node-gyp']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/node-gyp',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/node-gyp',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ 'DirWriter._create (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23)',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:297:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "node-gyp"
npm ERR! cwd /Users/hjsung/Documents/Dev/nodejs/myblog.com
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! path /usr/local/lib/node_modules/node-gyp
npm ERR! fstream_path /usr/local/lib/node_modules/node-gyp
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/node-gyp'
npm ERR! fstream_stack DirWriter._create (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23)
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hjsung/Documents/Dev/nodejs/myblog.com/npm-debug.log
npm ERR! not ok code 0
make: **\* [update] Error 3

sudo로 실행하면... 파일들이 이후에도 root소유로 잡혀서 index.markdown편집할때도 sudo로 해줘야되던데...

**Comment by andrwj** [comment]
node를 맥에 설치할 때 brew로 설치 하거나 직접 컴파일해서 /usr/local 아래로 설치할때, "sudo" 상태에서 설치하면 node의 소유권이 'root' 로 설정됩니다.  따라서, 설치 된 이후에 전역 모듈을 넣거나 변경을 가할 때마다 root 권한을 필요로 하는건 하루프레스의 제약사항이라기보다 시스템 설정에 따른 사항입니다.

해결 방법은 
-  현재 사용자 아이디로 /usr/local 전체 소유권을 변경하는 것입니다.  사용하고 있는 맥 시스템에 여러 사람이 같이 쓰는 상황이 아니라면 이 방법이 가장 간단한 방법입니다.

> sudo chown hjsung:staff -R /usr/local 
- 다른 사람과 같이 쓰거나 다른 아이디와 같이 시스템을 써야 한다면, node를  hjsung 아이디의 권한으로 실행할 수 있도록 nvm 을 설치해서 node 를 다시 설치하는 것입니다.

> cd ~
> git clone https://github.com/creationix/nvm.git
> cd nvm
> ./install.sh
> cd 
> nvm install v0.8.15
- 매번 명령을 할 때마다 sudo 권한을 얻어 실행하는 방법입니다.

**Comment by rhiokim** [comment]
nvm 저장소에도 권장하고 있지만
nvm 의 경우 설치 후에 .bash_profile 에 넣어 두시면 nvm 쉘을 띄울때마다 nvm 을 사용할 수 있게 됩니다.

```
$ git clone https://github.com/creationix/nvm.git ~/.nvm
$ echo ". ~/.nvm/nvm.sh
$ nvm
```

**Comment by hjazz** [comment]
답변 감사합니다.

**Comment by hjazz** [comment]
제가 node설치를 nvm으로 하지 않고 패키지 설치를 해서 그런가보군요...
