### ISSUE TITLE
haroopress 설치 후 deploy 질문입니다.

### ISSUE THREAD

**Issue by aimmvp** [rhiokim/haroopress#293]
![haroopress ](https://f.cloud.github.com/assets/1927756/32573/4c64c1f4-5028-11e2-8c46-130b36036074.png)

haroopress deploy 관련 문의 드립니다.

현재 aimmvp.github.com 에서는  github에서 기본으로 제공되는 페이지 확인이 가능한 상태입니다.
그리고 위에 첨부한 이미지처럼 설정 후에 make new-post -> 작성 -> make gen -> make preview 로 미리보기까지 확인했습니다.(status 는 publish 로 변경)

확인 후에 make deploy 를 해도 배포가 이루어 지지 않습니다.

설정 내용중에 잘못된 부분이나 확인해야 할 부분이 있을까요??

**Comment by rhiokim** [comment]
이미지의 내용을 포함한 절차는 모두 맞습니다.
생성해 놓은 aimmvp.github.com 저장소를 재 생성만하시고 아무것도 하지마시고 위의 절차를 다시 한번 진행해보세요.

make deploy 가 진행되면

https://github.com/haroopress/haroopress.github.com (하루프레스 공식 사이트 저장소) 와 같이 리소스 구조가 설정되어야 합니다.

**Comment by rhiokim** [comment]
혹시 위의 방법으로 해도 안되면 make deploy 과정중

```
haroo> git push origin master --force
```

부분 이후의 로그를 댓글로 부탁드립니다.

**Comment by aimmvp** [comment]
repository 를 삭제하고 다시 생성한 후에 다시 위의 절차대로 진행했는데, 안되어서 다시 댓글 남깁니다.
위에서 말씀하신 로그입니다.

> haroo> git push origin master --force¶
> 
> haroo> completed http://aimmvp.github.com
> haroo> open http://aimmvp.github.com ? [y/n]          y

**Comment by andrwj** [comment]
혹시나..해서 확인해보시길 바랍니다: **Github에 등록된 공개키**가 사용중인 계정의 ~/.ssh/ 아래에 위치해 있는지 살펴보세요. 
하루프레스의 현재 설정은 Github으로 전송할 때 오류가 나더라도 표시하지 않게되어있더라구요.

**Comment by aimmvp** [comment]
확인해보니까 공개키 파일(id_rsa.pub)도 있고, 공개키도 입력되어있습니다. 일단 배포까지의 절차상으로는 이상이 없다고 하시니까 git 관련된 부분을 다시 하나씩 확인 해보겠습니다

**Comment by andrwj** [comment]
`make deploy` 까지 한 상태라면, 수동으로 Github에 push 해보시면 문제의 원인을 유추하는데 도움이 될 것 같습니다.

```
$ cd _deploy
$ git push origin master --force
```

위의 명령에서 오류가 난다면 그건 Git 관련 문제가 되겠지요.

**Comment by aimmvp** [comment]
```
$ git push origin mater --force 
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

공개키가 있는데 push를 해보니까 오류가 나서 다시 공개키 생성을 하고 등록후에 다시 해보니까 잘 됩니다.!
감사합니다.
