### ISSUE TITLE
haroopress repository 백업 방법 문의 드립니다.

### ISSUE THREAD

**Issue by aimmvp** [rhiokim/haroopress#295]
로컬에 haroopress 를 세팅하고 사용하고 있습니다.

이번에 그 PC를 초기화 하고 다시 세팅하려고 하면서, 백업을 생각하게 되었습니다.

제가 생각하는 방법은
세팅되어있는 repository 를 통째로 백업받아서, 다시 세팅하는 방법밖에 모르겠는데,
혹시 다른 방법이 있거나 생각하고 있는 방법이 있으신지 문의 드립니다.

**Comment by rhiokim** [comment]
특별한 백업 방법은 없습니다. :-)

가이드를 드리자면
1. 블로그 환경설정 파일인 config.js 파일과 source/data 폴더만 백업하시면 됩니다.
2. 하루프레스를 다시 설치하고 config.js 를 먼저 복사하고
3. 설치과정에서 source/data 에 초기 데이터를 생성하는데 이 데이터를 삭제하고 백업한 source/data 를 복사해 넣으시면 됩니다.

좀더 고급 가이드를 드리자면

### Dropbox 로 사용자 데이터만 동기화하기
1. 기존의 하루프레스 디렉토리에 `source/data` 폴더를 dropbox 로 이동한다.
2. config.js 를 열어 `sourceDir` 에 이동한 dropbox 의 절대경로를 지정해준다.

이렇게 하면 데이터는 Dropbox 를 통해서 언제 어디서든지 동기화가 가능해지고 하루프레스를 다시 설치하고 싶다면 그냥 설치했던 하루프레스를 그냥 삭제하고 다시 설치하면 된다.

다만 설치 과정중에 설정한 정보를 그대로 사용하고 싶다면 
1. config.js 도 백업
2. 하루프레스를 다시 클론
3. 하루프레스 설치 시작
4. config.js 를 복원

마지막으로 한가지 방법이 더 있는데요. 이 방법은 Github 를 통해서 팀 블로깅을 할 때 유용합니다.

### Git 서브모듈로 관리하기

source/data 폴더에는 사용자가 생성하는 모든 데이터가 존재합니다.

`source/data/articles` : 포스팅 
`source/data/authors` : 저작자 정보 
`source/data/pages` : 페이지 스타일 포스팅
`source/data/favorites.markdown` : 즐겨찾기 목록

만약 `source/data/` 폴더를 별도의 git 저장소를 생성해서 서브모듈로 관리하면 더욱 편리합니다.

`/path/to/myharoopress/.git`-> git@github.com:my_github_id/**my_github_id.github.com.git**
`/path/to/myharoopress/source/data/.git` -> git@github.com:my_github_id/**my_haroopress_data.git**

**Comment by rhiokim** [comment]
해결 되셨는지 모르겠네요. ^^
일단 종료 처리합니다.
