### ISSUE TITLE
_deploy 하위 git 저장소 형식을 바꿔주세요. 발행이 안됩니다.

### ISSUE THREAD

**Issue by ghost** [rhiokim/haroopress#299]
make init 하고 중간 과정에 github 저장소 등록을 하고..

나중에 make gen, make deploy 하면 저장소에 아무것도 안올라갑니다.
처음에는 아이디랑 암호도 입력 안됐는데 어떻게 자기혼자 올리지?? 신기하다는 생각을 했는데..... 몇 일 삽질하니까 ... 프로그램 버그가 아닐까 의심이 되더라구요..

그래서 수동으로 make gh-pages 로 github 저장소를 등록하니 그 다음부터 deploy 잘 되... 는가 싶었죠?  기대는 무너졌습니다. ㅠㅠ

결국 하루프레스설치/_deplay/.git/config 파일을 열어서

git@ 형태가 아닌 일반

https://github.com/아이디/아이디.github.com.git 

형태로 주소를 바꿔주니까 제대로 동작하네요.

**Comment by rhiokim** [comment]
제대로 등록 안되었을 때 입력했던 저장소 주소를 알려주세요. :-)

**Comment by ghost** [comment]
지금 새로 설치하다가 robotskirt.o 에러가 나서....  예전건 기억이 안나는데 ;;;;

git@github??/mezeet/mezeet.github.com.git  중간에 잘 모르겠고 설치 안내에서 예시나오는데로 적었던 것 같아요.

**Comment by rhiokim** [comment]
위에서 조취한 방법과 같이 `_deploy` 폴더를 기준으로 저장소와 동기화됩니다.

`git://` 이나 `https://` 프로토콜은 지원하지 않고 `git@github.com:mezeet/mezeet.github.com.git` 형식만 지원합니다.
단, 시스템에 생성한 ssh-key 를 github.com 에 등록되어 있어야 합니다.

ssh-key 생성 및 등록 방법 : [https://help.github.com/articles/generating-ssh-keys](https://help.github.com/articles/generating-ssh-keys)

Mac OS X 10.8.4 / node v0.8.14 / git version 1.8.3.1 환경에서 `make gh-page` 로 위의 저장소를 지정해보니 `_deploy` 폴더에 다음과 같이 git 초기화와 remote 지정이 잘 지정되네요.

```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = false
[remote "origin"]
    url = git@github.com:mezeet/mezeet.github.com.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
[prompt]
    showinfo = true
```

**Comment by ghost** [comment]
아니... 이것도 방법을 안찾은 제 잘못이군요. ㅠㅠ @rhiokim 미안합니다.

**Comment by rhiokim** [comment]
아니에요. 메뉴얼도 그렇고 사용 방법도 접근성이 많이 부족하기 때문이라 생각합니다.
