### ISSUE TITLE
개인 서버로 운영 할 방법은 없나요?

### ISSUE THREAD

**Issue by thinkong** [rhiokim/haroopress#309]
make init 하면 무조건 github pages에 생성이 되는것으로 보이는데.. 이 단계를 건너 뛰고 개인 서버에 운영할 방법은 없나요? (제가 정보를 못찾은건지도 모르겠습니다만...)

**Comment by rhiokim** [comment]
make init 은 haroopress 를 해당 시스템에 설치하는 과정입니다.

make preview 는 로컬 웹 서버가 실행됩니다.

make deploy 를 할 경우 github pages 서비스로 배포됩니다.

make gen 을 하면 작성된 글들을 기준으로 path/to/haroopress/_public 폴더에 정적 파일들이 생기고
해당 디렉토리가 make preview 했을때의 docroot 가 됩니다.

**Comment by thinkong** [comment]
@rhiokim  답변 감사합니다..
