### ISSUE TITLE
make init error 

### ISSUE THREAD

**Issue by J2P** [rhiokim/haroopress#92]
git submodule update --init --recursive
Cloning into node_modules/markdown-blog...
The authenticity of host 'github.com (207.97.227.239)' can't be established.
RSA key fingerprint is .
Are you sure you want to continue connecting (yes/no)? 
Host key verification failed.
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:rhiokim/haroog-engine.git' into submodule path 'node_modules/markdown-blog' failed
make: **\* [init] Error 1

위와 같은 에러가 발생합니다.

**Comment by J2P** [comment]
아... 죄송합니다. 

처음에 clone 받을때 --recursive 옵션을 안줘서 그런거네요;;;

**Comment by rhiokim** [comment]
네 -_-;
